config/routes.rb
Yleistin::Application.routes.draw do

  devise_for :users, :token_authentication_key => 'authentication_key', :controllers => {:registrations => "devise/registrations", :sessions => "devise/sessions"}
  devise_scope :user do
    get "/users/sign_out", to: "devise/sessions#destroy", :via => [:get, :post]
    get "/users/sign_in", to: "home#index", :via => [:get, :post]
  end

  resource :home
  resource :user_answers do
    collection do
      get :save_answers
      get :compare
      get :reset
    end
  end

  match '/compare' , to: "user_answers#compare" , :via => [:get]
  match '/reset' , to: "user_answers#reset" , :via => [:get]

  root 'home#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :topic
  has_many :user_answers
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :questions
  has_many :user_performance
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_answers, :dependent => :destroy
  has_many :user_performances, :dependent => :destroy
end

app/models/user_answer.rb
class UserAnswer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
end

app/models/user_performance.rb
class UserPerformance < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #before_filter :authenticate_user!
  before_filter :home_variables

  def index
    @questions = Question.all
    random = rand(1...@questions.count)
    @rand_questions = @questions.order("RANDOM()").limit(random)
    $rand_questions = @rand_questions
    redirect_to "/compare" unless @user.blank?
  end

  private

  def home_variables
    @remote_ip = request.remote_ip
    #@remote_ip = "192.169.0.2"
    @user = User.find_by_current_sign_in_ip(@remote_ip)
  end

end

app/controllers/user_answers_controller.rb
class UserAnswersController < ApplicationController
  before_filter :u_answer_variables

  def save_answers
    user = User.find_by_current_sign_in_ip(@remote_ip)
    if user.blank?
      user = User.new(:current_sign_in_ip => @remote_ip, :up_range => params[:up_range],
                      :down_range => params[:down_range])
      user.save(:validate => false)
    end
    delete_user_answers(user) unless user.blank?
    answers = []
    params[:answers].split(',').each_with_index do |answer, index|
      answers << answer
    end
    user_answers = []
    params[:q_ids].split(',').each_with_index do |question, index|
      user_answers << UserAnswer.new(:question_id => question, :yes => answers[index] == '1' ? true : false,
                                     :no => answers[index] == '0' ? true : false, :user_id => user.id)
    end
    UserAnswer.import user_answers
    user_performance(user)
    render :text => 'ok'
  end

  def compare
    redirect_to root_path if @user.blank? and @link.blank?
    @user_performance = @user.user_performances unless @user.blank?
    @others_performance = []
    @your_performance = []
    @compare_topics = []
    unless @user_performance.blank?
      @user_performance.each do |u_performance|
        performances = UserPerformance.where('user_id != ? and topic_id = ?', @user.id, u_performance.topic_id)
        unless performances.blank?
          @your_performance << u_performance.performance
          @compare_topics << u_performance.topic.title
          performance_sum = performances.sum(:performance)
          @others_performance << (performance_sum.to_f / performances.count).to_f
        end
      end
    end

    @all_performances = []
    @all_topics = []
    Topic.all.each do |topic|
      total_topic_perform = UserPerformance.where(:topic_id => topic.id)
      unless total_topic_perform.blank?
        perform = total_topic_perform.sum(:performance)
        @all_performances << (perform / (total_topic_perform.count).to_f).to_f
        @all_topics << topic.title
      end
    end

  end

  def reset
    @user.destroy
    redirect_to root_path
  end

  private
  def delete_user_answers(user)
    user_answers = UserAnswer.where(:user_id => user.id).load
    unless user_answers.blank?
      user_answers.each do |ans|
        ans.destroy
      end
    end
  end

  def u_answer_variables
    @remote_ip = request.remote_ip
    #@remote_ip = "192.169.0.2"
    @user = User.find_by_current_sign_in_ip(@remote_ip)
    @users = User.all
    @link = params[:link]
    @user_answers = @user.user_answers unless @user.blank?
  end

  protected

  def user_performance(user)
    @user_answers = user.user_answers unless user.blank?
    @user_questions = Question.where(:id => [@user_answers.map { |u_ans| u_ans.question_id }]) unless @user_answers.blank?
    @uniq_questions = @user_questions.order('topic_id').pluck(:topic_id).uniq unless @user_questions.blank?
    @rand_topics = Topic.where(:id => [@uniq_questions]) unless @uniq_questions.blank?
    @performance_by_topic = @rand_topics.map { |topic| 100 }
    u_performance = []
    @rand_topics.each_with_index do |topic, index|
      asked_questions = @user_questions.where(:topic_id => topic.id)
      user_answer = UserAnswer.where(:user_id => user.id, :question_id => [asked_questions.map { |quest| quest.id }])
      user_answer.each do |u_ans|
        @performance_by_topic[index] = @performance_by_topic[index].to_f - (100/asked_questions.count.to_f).to_f if u_ans.no?
      end
      u_performance << UserPerformance.new(:user_id => user.id, :topic_id => topic.id, :performance => @performance_by_topic[index])
    end
    UserPerformance.import u_performance
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def topics_performance
    html = ''
    unless @user_performance.blank?
      @user_performance.each_with_index do |result, index|
        html = "#{result.performance}".to_s + ','.to_s + html.to_s
      end
    end
    return html
  end

  def topics_title
    html = ''
    unless @user_performance.blank?
      @user_performance.each_with_index do |user_performance, index|
        html = "'#{user_performance.topic.title.camelize.pluralize}'".to_s + ','.to_s + html.to_s
      end
    end
    return html
  end

  def compare_your_performance
    html = ''
    unless @your_performance.blank?
      @your_performance.each_with_index do |result, index|
        html = "#{result}".to_s + ','.to_s + html.to_s
      end
    end
    return html
  end

  def compare_others_performance
    html = ''
    unless @others_performance.blank?
      @others_performance.each_with_index do |result, index|
        html = "#{result}".to_s + ','.to_s + html.to_s
      end
    end
    return html
  end

  def compare_topics_title
    html = ''
    unless @compare_topics.blank?
      @compare_topics.each_with_index do |compare_topics, index|
        html = "'#{compare_topics.camelize.pluralize}'".to_s + ','.to_s + html.to_s
      end
    end
    return html
  end

  def compare_no_performance
    html = ''
    unless @all_performances.blank?
      @all_performances.each_with_index do |result, index|
        html = "#{result}".to_s + ','.to_s + html.to_s
      end
    end
    return html
  end

  def compare_no_topics_title
    html = ''
    unless @all_topics.blank?
      @all_topics.each_with_index do |compare_topics, index|
        html = "'#{compare_topics.camelize.pluralize}'".to_s + ','.to_s + html.to_s
      end
    end
    return html
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
= hidden_field_tag "question_count", 1
= hidden_field_tag "question_limit", @rand_questions.count
= hidden_field_tag "yes_count", 0
= hidden_field_tag "no_count", 0
= hidden_field_tag "up_count", 0
= hidden_field_tag "down_count", 100
= hidden_field_tag "add_subtract_count", (100.0/(@rand_questions.count).to_f).to_f.round(2)
.row
  .highlight.col-md-7.mainQuestCont
    #shareCircle{style: 'display: none'}
      %h3 That's it!!!
      %p
        .shareCircle
    #questionsContainer
      = hidden_field_tag "q_ids" , @rand_questions.map(&:id).join(",")
      -@rand_questions.each_with_index do |question, index|
        .randQuest{style: "display: #{index == 0 ? 'block': 'none'}",:id => "randQuest_#{index + 1}"}
          %h2#qNumber
            Q: #{index + 1}
          #question
            Do You Know
            %span.qTitle #{question.title}?
      %p
        %a.btn.btn-primary.btn-default.submitAnswer#yes{href: "javascript:" ,role: "button"} Yes
        %a.btn.btn-primary.btn-default.submitAnswer#no{href: "javascript:",role: "button"} No
  .highlight.col-md-4
    %h5 Your General Knowledge Estimated
    %p
      %span#gKwldgEstUp 0 -
      %span#gKwldgEstDown 100%
  #loaderDiv{:style => "display: none"}
    %img.ajax-loader{src: "/assets/ajax-loader.gif", title: "LOADING"}/
  #compareOthers.highlight.col-md-4{:style => "display: none"}
    %a.btn.btn-success{href: "/compare"}
      %h3 Compare to others

:javascript
  $(document).ready(function() {
    var answers;
    answers = new Array();
    $('.submitAnswer').click(function() {
      var a_count, d_count, l_count, n_count, q_count, q_ids, share_text, share_url, type, u_count, y_count;
      type = $(this).attr('id');
      l_count = parseInt($('#question_limit').val());
      q_count = parseInt($('#question_count').val());
      y_count = parseInt($('#yes_count').val());
      n_count = parseInt($('#no_count').val());
      u_count = parseFloat($('#up_count').val());
      d_count = parseFloat($('#down_count').val());
      a_count = parseFloat($('#add_subtract_count').val());
      if (parseInt(q_count) <= l_count) {
        $('#question_count').val(parseInt(q_count + 1));
        if (parseInt(q_count + 1) <= l_count) {
          $('#randQuest_' + q_count).css('display', 'none');
          $('#randQuest_' + parseInt(q_count + 1)).css('display', 'block');
        }
        if (type === 'yes') {
          $('#yes_count').val(parseInt(y_count + 1));
          $('#gKwldgEstUp').html(parseFloat(u_count + a_count).toFixed(2) + ' -');
          $('#up_count').val(parseFloat(u_count + a_count).toFixed(2));
          return answers.push(1);
        } else if (type === 'no') {
          $('#no_count').val(parseInt(n_count + 1));
          $('#gKwldgEstDown').html(parseFloat(d_count - a_count).toFixed(2) + '%');
          $('#down_count').val(parseFloat(d_count - a_count).toFixed(2));
          return answers.push(0);
        }
      } else {
        $('#loaderDiv').show();
        q_ids = $('#q_ids').val();
        $.ajax({
          url: '/user_answers/save_answers?q_ids=' + q_ids + '&answers=' + answers + '&up_range=' + u_count + '&down_range=' + d_count,
          type: 'get',
          dataType: 'html',
          processData: false,
          success: function(data) {
            $('#shareCircle').show();
            $('#compareOthers').show();
            $('#loaderDiv').hide();
            return $('#questionsContainer').hide();
          }
        });

        //share source http://jquery-plugins.net/share-button-fast-and-beautiful-social-share-buttons
        share_url = window.location + 'compare?link=true';
        share_text = $("#up_count").val() + ' - ' + $("#down_count").val();
        return $(".shareCircle").share({
          title: 'Yleistin',
          image: 'http://carrot.is/img/fb-share.jpg',
          app_id: '561967870564815',
          background: 'rgba(255,255,255,.5)',
          color: '#3B2B45',
          url: share_url,
          text: "My general knowledge ranges " + share_text + " , checkout out yours at " + share_url + ". #Yleistin",
          link: share_url,
        });
      }
    });
  });

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navbar.html.haml
%header.navbar.navbar-inverse.navbar-fixed-top.bs-docs-nav{role: "banner"}
  .container
    %nav.bs-docs-nav.navbar-collapse{role: "navigation"}
      %ul.nav.navbar-nav
        %li
          %a{href: ""} Yleistin
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
            Language
            %b.caret
          %ul.dropdown-menu
            %li
              %a{href: "#"} English
            %li
              %a{href: "#"} Finnish
            %li.divider
      -#%ul.nav.navbar-nav.navbar-right
      -#  %li
      -#    %a{href: "/users/sign_out"} Sign Out

app/views/layouts/_navigation.html.haml
= link_to "Vaihtais.in", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to 'Toiveeni', wishes_path
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
    - if current_user.has_role? :admin
      %li
        = link_to 'Admin', users_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "yleistin"
      / for Google
      %meta{:name => 'description', :content => 'Yleistin: Test your general knowledge'}
      %meta{:name => 'og:image',  :content => 'http://carrot.is/img/fb-share.jpg'}
      %meta{content: "561967870564815", property: "fb:app_id"}/
      %meta{:content => content_for?(:description) ? yield(:description) : "yleistin", :name => "description"}
        = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => false
        = javascript_include_tag "application", "data-turbolinks-track" => false
        = csrf_meta_tags
        = yield(:head)
  #wrapper
  #container
    %nav{role: "navigation"}
      = render "layouts/navbar"
    //nav
    - flash.each do |name, msg|
      - if msg.is_a?(String)
        %div{:class => "alert alert-dismissable alert-#{name == :notice ? "success" : "error"}"}
          %a.close{"data-dismiss" => "alert"} ×
          = content_tag :div, msg, :id => "flash_#{name}"
    %section#section1.section{"data-section" => "1"}
      .container-fluid
        .row-fluid
          = yield
        / /row-fluid
      / /container-fluid
    / /section

app/views/layouts/application_bac.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yleistin</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user_answers/compare.html.haml
.row
  .highlight.col-md-7.mainQuestCont
    %h3 Comparison
    - unless @user.blank?
      :javascript
         //Self comparison
         $(function () {
                 $('#compareContainer').highcharts({
                     chart: {
                         type: 'column'
                     },
                     title: {
                         text: 'Performance Meter'
                     },
                     subtitle: {
                         text: 'Your Performance in different topics'
                     },
                     xAxis: {
                         categories: [
                           #{topics_title}
                         ],
                         labels: {
                                             rotation: -45,
                                             align: 'right',
                                             style: {
                                                 fontSize: '13px',
                                                 fontFamily: 'Verdana, sans-serif'
                                             }
                                 }
                     },
                     yAxis: {
                         min: 0,
                         title: {
                             text: 'Percentage (%)'
                         }
                     },
                     tooltip: {
                         headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                         pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                             '<td style="padding:0"><b>{point.y:.1f} % </b></td></tr>',
                         footerFormat: '</table>',
                         shared: true,
                         useHTML: true
                     },
                     plotOptions: {
                         column: {
                             pointPadding: 0.2,
                             borderWidth: 0
                         }
                     },
                     series: [{
                         name: 'Performance',
                         data: [#{topics_performance}]

                     }]
                 });
             });



    #compareContainer
    - if @users.count > 1 and @link.blank?
      #compareOtherContainer
      :javascript
        // Comparison with other
        $(function () {
           $('#compareOtherContainer').highcharts({
                       chart: {
                           type: 'column'
                       },
                       title: {
                           text: 'Performance Meter'
                       },
                       subtitle: {
                           text: 'Your Performance in comparison to others(average) in different topics'
                       },
                       xAxis: {
                           categories: [
                             #{compare_topics_title}
                           ],
                           labels: {
                                      rotation: -45,
                                      align: 'right',
                                      style: {
                                        fontSize: '13px',
                                        fontFamily: 'Verdana, sans-serif'
                                      }
                                   }
                       },
                       yAxis: {
                           min: 0,
                           title: {
                               text: 'Percentage (%)'
                           }
                       },
                       tooltip: {
                           headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                           pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                               '<td style="padding:0"><b>{point.y:.1f} % </b></td></tr>',
                           footerFormat: '</table>',
                           shared: true,
                           useHTML: true
                       },
                       plotOptions: {
                           column: {
                               pointPadding: 0.2,
                               borderWidth: 0
                           }
                       },
                       series: [{
                           name: 'You',
                           data: [#{compare_your_performance}]

                       },
                       {
                           name: 'Others',
                           data: [#{compare_others_performance}]

                       }
                       ]
                   });
        });

    - unless @link.blank?
      #compareNoContainer
      :javascript
        // Comparison with other
        $(function () {
                 $('#compareNoContainer').highcharts({
                             chart: {
                                 type: 'column'
                             },
                             title: {
                                 text: 'Overall Performance Meter'
                             },
                             subtitle: {
                                 text: 'Overall Performances(average) of other peoples in different topics'
                             },
                             xAxis: {
                                 categories: [
                                   #{compare_no_topics_title}
                                 ],
                                 labels: {
                                            rotation: -45,
                                            align: 'right',
                                            style: {
                                              fontSize: '13px',
                                              fontFamily: 'Verdana, sans-serif'
                                            }
                                         }
                             },
                             yAxis: {
                                 min: 0,
                                 title: {
                                     text: 'Percentage (%)'
                                 }
                             },
                             tooltip: {
                                 headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                                 pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                                     '<td style="padding:0"><b>{point.y:.1f} % </b></td></tr>',
                                 footerFormat: '</table>',
                                 shared: true,
                                 useHTML: true
                             },
                             plotOptions: {
                                 column: {
                                     pointPadding: 0.2,
                                     borderWidth: 0
                                 }
                             },
                             series: [
                             {
                                 name: 'Performance',
                                 data: [#{compare_no_performance}]

                             }
                             ]
                 });
        });


  .highlight.col-md-4
    - if @user.blank?
      - unless @link.blank?
        %h5 Try out Yourself
        %a.btn.btn-success{href: "/"}
          %h3 Try out Yourself
      -else
        %h5 Reload Reset
        %a.btn.btn-success{href: "/reset"}
          %h3 Reload Reset

    -else
      %h5 Reload Reset
      %a.btn.btn-success{href: "/reset"}
        %h3 Reload Reset